ovosh1 = input("1 овощ: ")
ovosh2 = input("2 овощ: ")
ovosh3 = input("3 овощ: ")
ovosh1m = ovosh1.lower()
ovosh2m = ovosh2.lower()
ovosh3m = ovosh3.lower()
ovosh1b = ovosh1.upper()
ovosh2b = ovosh2.upper()
ovosh3b = ovosh3.upper()
ovosh1n = ovosh1.title()
ovosh2n = ovosh2.title()
ovosh3n = ovosh3.title()
kolv1 = int(input("сколько " + ovosh1 + ": "))
kolv2 = int(input("сколько " + ovosh2 + ": "))
kolv3 = int(input("сколько " + ovosh3 + ": "))
print("{} {} ({}, {})".format(kolv1, ovosh1m, ovosh1b, ovosh1n))
print("{} {} ({}, {})".format(kolv2, ovosh2m, ovosh2b, ovosh2n))
print("{} {} ({}, {})".format(kolv3, ovosh3m, ovosh3b, ovosh3n))