def mal(slov):
    return slov.lower()
def dolsh(slov):
    return slov.upper()
def norm(slov):
    return slov.title()
ovosh1 = input("1 овощ: ")
ovosh2 = input("2 овощ: ")
ovosh3 = input("3 овощ: ")
ovosh1m = mal(ovosh1)
ovosh2m = mal(ovosh2)
ovosh3m = mal(ovosh3)
ovosh1b = dolsh(ovosh1)
ovosh2b = dolsh(ovosh2)
ovosh3b = dolsh(ovosh3)
ovosh1n = norm(ovosh1)
ovosh2n = norm(ovosh2)
ovosh3n = norm(ovosh3)
kolv1 = int(input("сколько " + ovosh1 + ": "))
kolv2 = int(input("сколько " + ovosh2 + ": "))
kolv3 = int(input("сколько " + ovosh3 + ": "))
print("{} {} ({}, {})".format(kolv1, ovosh1m, ovosh1b, ovosh1n))
print("{} {} ({}, {})".format(kolv2, ovosh2m, ovosh2b, ovosh2n))
print("{} {} ({}, {})".format(kolv3, ovosh3m, ovosh3b, ovosh3n))